apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
  SPRING_DATASOURCE_USERNAME: urlshortener
  SPRING_DATASOURCE_PASSWORD: change-me
  JWT_SECRET: change-this-super-long-secret-for-production
  REDIS_PASSWORD: ""
